### ISSUE TITLE
Obstacle detection for Follow the Gap

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/Autonomy#4]
Use the RealSense to detect obstacles and forward their boundaries to our Follow the Gap implementation.

GanttStart: 2022-04-07
GanttDue: 2022-05-05

**Comment by Levi-Lesches** [comment]
@jmcmah10, are we not going with this method?

**Comment by Levi-Lesches** [comment]
ROS or a pathfinding library should be able to handle this
